openapi: 3.1.0
info:
  title: Global AI Legal & Forensic Expert
  version: 1.0.0
servers:
  - url: https://gpt-legal-backend.onrender.com
    description: Render Production Server

paths:
  /:
    get:
      summary: Root
      operationId: root__get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}

  /reflexion/:
    post:
      summary: Ejecutar Reflexion
      operationId: ejecutar_reflexion_reflexion__post
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ReflexionInput"
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ReflexionOutput"
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HTTPValidationError"

  /vision/:
    post:
      summary: Analizar Imagen
      operationId: analizar_imagen_vision__post
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/VisionInput"
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/VisionOutput"
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HTTPValidationError"

  /prediccion/:
    post:
      summary: Predecir
      operationId: predecir_prediccion__post
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/BayesInput"
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HTTPValidationError"

  /bcn/buscar:
    get:
      summary: Buscar Norma
      operationId: buscar_norma_bcn_buscar_get
      parameters:
        - name: palabra
          in: query
          required: true
          schema:
            type: string
            title: Palabra
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HTTPValidationError"

  /bcn/norma/{id_norma}:
    get:
      summary: Obtener Norma
      operationId: obtener_norma_bcn_norma__id_norma__get
      parameters:
        - name: id_norma
          in: path
          required: true
          schema:
            type: integer
            title: Id Norma
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HTTPValidationError"

  /bcn/text-search:
    get:
      summary: Búsqueda textual en legislación chilena
      operationId: buscarTextoLegal
      parameters:
        - name: palabra
          in: query
          required: true
          schema:
            type: string
            title: Palabra clave a buscar
      responses:
        '200':
          description: Resultados de búsqueda legal simulados
          content:
            application/json:
              schema:
                type: object
                properties:
                  palabra:
                    type: string
                  resultados:
                    type: array
                    items:
                      type: object
                      properties:
                        norma_id:
                          type: integer
                        extracto:
                          type: string

components:
  schemas:
    BayesInput:
      type: object
      title: BayesInput
      required:
        - contexto
      properties:
        contexto:
          type: string
          title: Contexto

    HTTPValidationError:
      type: object
      title: HTTPValidationError
      properties:
        detail:
          type: array
          title: Detail
          items:
            $ref: "#/components/schemas/ValidationError"

    ReflexionInput:
      type: object
      title: ReflexionInput
      required:
        - documento_analizado
        - criterios
      properties:
        documento_analizado:
          type: string
          title: Documento Analizado
        criterios:
          type: array
          title: Criterios
          items:
            type: string

    ReflexionOutput:
      type: object
      title: ReflexionOutput
      required:
        - verificacion_integral
        - coherencia_estructural
        - consistencia_semantica
        - ajustes_realizados
      properties:
        verificacion_integral:
          type: string
          title: Verificacion Integral
        coherencia_estructural:
          type: string
          title: Coherencia Estructural
        consistencia_semantica:
          type: string
          title: Consistencia Semantica
        ajustes_realizados:
          type: array
          title: Ajustes Realizados
          items:
            type: string

    ValidationError:
      type: object
      title: ValidationError
      required:
        - loc
        - msg
        - type
      properties:
        loc:
          type: array
          title: Location
          items:
            anyOf:
              - type: string
              - type: integer
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type

    VisionInput:
      type: object
      title: VisionInput
      required:
        - image_url
        - prompt
      properties:
        image_url:
          type: string
          format: uri
          title: Image Url
        prompt:
          type: string
          title: Prompt

    VisionOutput:
      type: object
      title: VisionOutput
      required:
        - resultado
        - resumen
      properties:
        resultado:
          type: string
          title: Resultado
        resumen:
          type: string
          title: Resumen
