openapi: 3.1.0
info:
  title: GPT Legal Forensic API
  description: API para análisis legal automatizado con múltiples módulos...
  version: "1.0"
servers:
  - url: https://gpt-legal-backend.onrender.com
    description: Servidor público en Render

paths:
  /:
    get:
      operationId: readRoot
      summary: Verificar estado del backend
      responses:
        '200':
          description: Respuesta básica de estado
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

  /reflexion/reflexion/:
    post:
      operationId: reflexionar
      summary: Realizar reflexión jurídica
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [documento_analizado, criterios]
              properties:
                documento_analizado:
                  type: string
                criterios:
                  type: array
                  items:
                    type: string
      responses:
        '200':
          description: Resultado del análisis reflexivo
          content:
            application/json:
              schema:
                type: object
                properties:
                  verificacion_integral:
                    type: string
                  coherencia_estructural:
                    type: string
                  consistencia_semantica:
                    type: string
                  ajustes_realizados:
                    type: array
                    items:
                      type: string

  /vision/vision/:
    post:
      operationId: analizarImagen
      summary: Análisis visual forense de una imagen
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [image_id]
              properties:
                image_id:
                  type: string
      responses:
        '200':
          description: Análisis visual
          content:
            application/json:
              schema:
                type: object
                properties:
                  vision:
                    type: string

  /prediccion/api/prediccion/:
    post:
      operationId: predecirRiesgo
      summary: Predicción de riesgo utilizando análisis bayesiano
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [contexto]
              properties:
                contexto:
                  type: string
      responses:
        '200':
          description: Resultado de la predicción
          content:
            application/json:
              schema:
                type: object
                properties:
                  riesgo:
                    type: string

  /bcn/api/bcn/norma/{id_norma}:
    get:
      operationId: obtenerNormaBcn
      summary: Obtener norma legal por ID desde BCN
      parameters:
        - name: id_norma
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Norma legal obtenida
          content:
            application/json:
              schema:
                type: object
                properties:
                  norma:
                    type: object
                    additionalProperties: true

  /legislacion/buscar:
    get:
      operationId: buscarNorma
      summary: Buscar norma legal en BCN por palabra clave
      parameters:
        - name: palabra
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Resultados de búsqueda
          content:
            application/json:
              schema:
                type: object
                properties:
                  resultados:
                    type: array
                    items:
                      type: object
                      additionalProperties: true

  /legislacion/norma/{id_norma}:
    get:
      operationId: obtenerNormaLegislacion
      summary: Obtener norma desde legislacion_bcn por ID
      parameters:
        - name: id_norma
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Norma encontrada
          content:
            application/json:
              schema:
                type: object
                properties:
                  norma:
                    type: object
                    additionalProperties: true

  /bcn/text-search:
    get:
      operationId: buscarTextoBcn
      summary: Búsqueda textual en legislación BCN
      parameters:
        - name: palabra
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Resultados de la búsqueda textual
          content:
            application/json:
              schema:
                type: object
                properties:
                  resultados:
                    type: array
                    items:
                      type: object
                      additionalProperties: true

  /forensics/api/forensics/search:
    get:
      operationId: buscarForensics
      summary: Realizar búsqueda de beneficiarios o GAFI en análisis forense
      parameters:
        - name: pregunta
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Resultados del análisis forense
          content:
            application/json:
              schema:
                type: object
                properties:
                  resultados:
                    type: array
                    items:
                      type: object
                      additionalProperties: true

  /status/status/json:
    get:
      operationId: obtenerStatus
      summary: Obtener el estado actual del sistema
      responses:
        '200':
          description: Estado general del backend
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
