openapi: 3.1.0
info:
  title: GPT Legal Forensic API
  version: "1.0"
servers:
  - url: https://gpt-legal-backend.onrender.com
    description: Render backend deployment

paths:
  /:
    get:
      operationId: getRoot
      summary: Estado del sistema
      responses:
        "200":
          description: Respuesta básica
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

  /reflexion/reflexion/:
    post:
      operationId: postReflexion
      summary: Ejecutar reflexión
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ReflexionInput"
      responses:
        "200":
          description: Análisis exitoso
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ReflexionOutput"
        "422":
          description: Error de validación

  /vision/vision/:
    post:
      operationId: postVision
      summary: Analizar imagen
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/VisionInput"
      responses:
        "200":
          description: Resultado del análisis
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/VisionOutput"
        "422":
          description: Error de validación

  /prediccion/api/prediccion/:
    post:
      operationId: postPrediccion
      summary: Ejecutar predicción bayesiana
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/BayesInput"
      responses:
        "200":
          description: Resultado de la predicción
          content:
            application/json:
              schema:
                type: object
                properties:
                  resultado:
                    type: string
        "422":
          description: Error de validación

  /bcn/api/bcn/norma/{id_norma}:
    get:
      operationId: getNormaBcn
      summary: Obtener norma BCN
      parameters:
        - name: id_norma
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Norma encontrada
          content:
            application/json:
              schema:
                type: object
                properties:
                  id_norma:
                    type: integer
                  contenido:
                    type: string
        "422":
          description: Error de validación

  /legislacion/buscar:
    get:
      operationId: buscarLegislacion
      summary: Buscar norma por palabra clave
      parameters:
        - name: palabra
          in: query
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Resultados encontrados
          content:
            application/json:
              schema:
                type: object
                properties:
                  resultados:
                    type: array
                    items:
                      type: string
        "422":
          description: Error de validación

  /legislacion/norma/{id_norma}:
    get:
      operationId: getLegislacionNorma
      summary: Obtener detalle de norma legislativa
      parameters:
        - name: id_norma
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Detalle de la norma
          content:
            application/json:
              schema:
                type: object
                properties:
                  id_norma:
                    type: integer
                  texto:
                    type: string
        "422":
          description: Error de validación

  /bcn/text-search:
    get:
      operationId: buscarTextoLegal
      summary: Búsqueda textual en legislación chilena
      parameters:
        - name: palabra
          in: query
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Resultados de búsqueda
          content:
            application/json:
              schema:
                type: object
                properties:
                  palabra:
                    type: string
                  resultados:
                    type: array
                    items:
                      type: object
                      properties:
                        norma_id:
                          type: integer
                        extracto:
                          type: string
        "422":
          description: Error de validación

  /forensics/api/forensics/search:
    get:
      operationId: buscarForensics
      summary: Buscar pregunta en proxy forense
      parameters:
        - name: pregunta
          in: query
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Respuesta forense
          content:
            application/json:
              schema:
                type: object
                properties:
                  respuesta:
                    type: string
        "422":
          description: Error de validación

  /status/status/json:
    get:
      operationId: getStatusJson
      summary: Obtener estado del sistema
      responses:
        "200":
          description: Estado actual
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string

components:
  schemas:
    ReflexionInput:
      type: object
      required: [documento_analizado, criterios]
      properties:
        documento_analizado:
          type: string
        criterios:
          type: array
          items:
            type: string

    ReflexionOutput:
      type: object
      required: [verificacion_integral, coherencia_estructural, consistencia_semantica, ajustes_realizados]
      properties:
        verificacion_integral:
          type: string
        coherencia_estructural:
          type: string
        consistencia_semantica:
          type: string
        ajustes_realizados:
          type: array
          items:
            type: string

    VisionInput:
      type: object
      required: [image_id]
      properties:
        image_id:
          type: string

    VisionOutput:
      type: object
      required: [vision]
      properties:
        vision:
          type: string

    BayesInput:
      type: object
      required: [contexto]
      properties:
        contexto:
          type: string
