openapi: 3.1.0
info:
  title: GPT Legal Backend
  version: 1.0.0
  description: API de backend legal para reflexiones jurídicas, visión forense, y consultas a legislación chilena.

servers:
  - url: http://localhost:8000
    description: Servidor local de desarrollo

paths:
  /reflexion/ejecutar:
    post:
      operationId: ejecutarReflexion
      summary: Ejecutar reflexión jurídica
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                pregunta:
                  type: string
      responses:
        '200':
          description: Respuesta con reflexión
          content:
            application/json:
              schema:
                type: object
                properties:
                  respuesta:
                    type: string

  /vision/procesar:
    post:
      operationId: procesarVisionForense
      summary: Procesar visión forense
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                imagen:
                  type: string
                  format: binary
      responses:
        '200':
          description: Resultado de visión forense
          content:
            application/json:
              schema:
                type: object
                properties:
                  resultado:
                    type: string

  /prediccion/estimar:
    post:
      operationId: estimarPrediccion
      summary: Realiza predicción bayesiana sobre datos legales
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                datos:
                  type: object
      responses:
        '200':
          description: Resultado de la predicción
          content:
            application/json:
              schema:
                type: object
                properties:
                  resultado:
                    type: string

  /bcn/extraer:
    post:
      operationId: extraerDesdeBcn
      summary: Extrae texto legal desde una URL del BCN
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                url:
                  type: string
      responses:
        '200':
          description: Texto legal extraído
          content:
            application/json:
              schema:
                type: object
                properties:
                  texto:
                    type: string

  /bcn/buscar:
    post:
      operationId: buscarEnBcn
      summary: Realiza búsqueda textual en legislación BCN
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                consulta:
                  type: string
      responses:
        '200':
          description: Resultados de búsqueda
          content:
            application/json:
              schema:
                type: object
                properties:
                  resultados:
                    type: array
                    items:
                      type: string

  /legislacion/buscar:
    post:
      operationId: buscarLegislacion
      summary: Buscar legislación chilena por número o palabras clave
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                query:
                  type: string
      responses:
        '200':
          description: Detalles de la legislación encontrada
          content:
            application/json:
              schema:
                type: object
                properties:
                  resultado:
                    type: string

  /forensics/gafi:
    post:
      operationId: obtenerInformeForense
      summary: Obtiene resultados forenses según criterios GAFI
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                caso:
                  type: string
      responses:
        '200':
          description: Informe forense GAFI
          content:
            application/json:
              schema:
                type: object
                properties:
                  informe:
                    type: string

  /status/ping:
    get:
      operationId: pingStatus
      summary: Verificar estado del sistema
      responses:
        '200':
          description: Estado OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
